name: FoliaStuff
version: '1.1'
main: 'me.paul.foliastuff.other.FoliaStuff'
description: Wheel, Cases, Goated on the Sticks
folia-supported: true
load: POSTWORLD

api-version: '1.20'
bootstrapper: me.paul.foliastuff.other.FoliaBootstrapper
depend: [PlaceholderAPI]

authors:
  - paulyg

commands:
  home:
    description: TP to home
  sethome:
    description: Set home
  wheel:
    description: Interact with the wheel
    default: true
  wheeleffect:
    description: Test wheel effect
    op: true
    aliases: [we]
  displayname:
    description: Change display name
    aliases: [dn]
  image:
    description: Display image/gif
    aliases: [gif]
    op: true
  case:
    description: open a case smiley
    op: true
  test:
    description: Test cmd
    op: true
